#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

echo "==> Installing Bundler…"
gem install bundler

if [ -f "Gemfile" ]; then
  echo "==> Installing gem dependencies…"
  bundle check --path vendor/gems >/dev/null 2>&1  || {
    bundle install --path vendor/gems --quiet --without production
  }
fi
