#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

echo "==> Getting ri documentation for all your gems"
gem rdoc --all --ri --no-rdoc

echo "==> RiBot is ready to serve!"
echo "    Run script/run"
